title: SamuraiOwl
description: "The officially fowl website for SamuariOwl, an author, gamedev, artist, YouTuber, and musician."
author:
  name: "SamuraiOwl"
  email: "samuraiowl00@gmail.com"
  url: "https://samuraiowl.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "SamuraiOwl"
year : "2020"
