title: Samurai Owl
description: "The officially fowl website for Samuari Owl"
author:
  name: "Samurai Owl"
  email: "samuraiowl00@gmail.com"
  url: ""

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Samurai Owl"
year : "2018"
